### ISSUE TITLE
OMEMO encryption

### ISSUE THREAD

**Issue by butyoutried** [BombusMod/BombusMod#125]
Please add support for [XEP-0384](https://xmpp.org/extensions/xep-0384.html).

See also: https://conversations.im/omemo/

**Comment by vitalyster** [comment]
How much you will pay?

**Comment by micwoj92** [comment]
@vitalyster are you interested in using some crowdfunding such as bountysource.com?

**Comment by vitalyster** [comment]
@micwoj92 some?

**Comment by micwoj92** [comment]
I meant bountysource as example because it is most popular of such software.

**Comment by sjehuda** [comment]
> How much you will pay?

I suggest for the developers to create a bounty page.

See https://power2people.org/projects/overview/
Via: https://aros.sourceforge.io/

**Comment by vitalyster** [comment]
@sjehuda how much you will pay for my time to set up a "bounty page" and so on?
If you need some feature - it is your job to find resources for that, not mine.
I'm happy to review pull requests for free.

**Comment by sjehuda** [comment]
I can create a bountly page for BombusMod.

Are there more features that were requested in the past, other than
OMEMO?

**Comment by vitalyster** [comment]
Please don't waste your and my time if you do not want to do an actual work.

**Comment by sjehuda** [comment]
Quite the opposite. I do not intend to waste time.

I have stated, that I think that it would be beneficial to create a
bounty page which would *save* time.

Suppose there is a bounty page. The page would communicate these:

**BombusMod Bounties**

1. This is a list of potential features.
2. The listed features are currently not of high priority.
3. If you want to prioritize a feature, this is how much it would cost.

I am willing to create a bounty page, if you want.

**Comment by vitalyster** [comment]
@sjehuda list of potential features discussed here on GitHub Discussions and Issues, we no need in additional external services. If someone willing to pay for the feature it can use Github Sponsorship, contact me directly, hire another developers themself, etc. Please, stop, you are wasting your own time.
