### ISSUE TITLE
crashes on go back key

### ISSUE THREAD

**Issue by treakiandroid** [BombusMod/BombusMod#13]
latest android fdroid Version

when you are in one of that full screen text edit views and you press the back button the entier thing crashes.

havent tested any further

fix that first

**Comment by vitalyster** [comment]
Can you please provide a backtrace (from catlog app with root or so)?

**Comment by vitalyster** [comment]
Issues with text views are fixed in [0.9.1404 release](https://github.com/BombusMod/BombusMod/releases/tag/0.9.1404)
