### ISSUE TITLE
XEP-0156 _xmppconnect is vulnerable to MITM

### ISSUE THREAD

**Issue by moparisthebest** [BombusMod/BombusMod#130]
Context: https://mail.jabber.org/pipermail/standards/2022-February/038759.html

Vulnerable code: https://github.com/BombusMod/BombusMod/blob/6672861668979fb3612ea5933d437f68c1df4931/src/main/java/io/DnsSrvResolver.java#L61

**Comment by vitalyster** [comment]
Thanks! But this code is unused and was only used for some experiments long time ago. [Removed](https://github.com/BombusMod/BombusMod/commit/a5479bbe1febb8207e5f536d05d9e517f96a88b4) anyway
