### ISSUE TITLE
robovm-gradle-plugin - fails to build

### ISSUE THREAD

**Issue by licaon-kter** [BombusMod/BombusMod#190]
```
FAILURE: Build failed with an exception.

* What went wrong:
'void org.apache.commons.compress.archivers.zip.ZipFile.<init>(java.nio.channels.SeekableByteChannel)'
```

ref: https://issuetracker.google.com/issues/213757977

Fix was to remove it from https://github.com/BombusMod/BombusMod/blob/0.9.1423/build.gradle#L12

**Comment by vitalyster** [comment]
Can I check full build log with that failure somewhere?

**Comment by licaon-kter** [comment]
log: [org.bombusmod_1423.log.gz](https://github.com/BombusMod/BombusMod/files/12584299/org.bombusmod_1423.log.gz)

**Comment by vitalyster** [comment]
Seems to be already fixed in MobiVM in the next version - https://github.com/MobiVM/robovm/issues/746
