### ISSUE TITLE
Dynamic versionName breaks F-Droid autoupdate

### ISSUE THREAD

**Issue by licaon-kter** [BombusMod/BombusMod#191]
ref: https://gitlab.com/fdroid/fdroiddata/-/commit/7700daf57f48f6d5d59ef0d3b8065aad070f6a9b

ref: https://github.com/BombusMod/BombusMod/commit/3e6345b382165a0ff66585a2b3ae7f14ccdb7cb1#diff-197b190e4a3512994d2cebed8aff5479ff88e136b8cc7a4b148ec9c3945bd65aR17

**Comment by vitalyster** [comment]
That seems an issue on your side

**Comment by licaon-kter** [comment]
Ok, so we'll have to disable autoupdates. Feel free to open a  MR for new releases.

**Comment by licaon-kter** [comment]
Fixed in https://gitlab.com/fdroid/fdroiddata/-/commit/9f2273e840dac8f82beff5ea3f72637c68f17afb
