### ISSUE TITLE
Please please a J2ME version?

### ISSUE THREAD

**Issue by mrc2rules** [BombusMod/BombusMod#91]
Hello! Is there a still working J2ME bombus client? I've been looking for one, and the only one i found is named 2go. If you guys have one that still works, please let me know. A lot of us are eager to have a client ☺️

**Comment by vitalyster** [comment]
j2me version was in Ovi/Opera Store, that store may still work, try this? http://ovi.sigma.apps.bemobi.com/en_us/bombusmod_bombusmod_n1.html?pos=1
